### ISSUE TITLE
Issue Related to agent?.createVerifiablePresentation()

### ISSUE THREAD

**Issue by vijay05155** [veramolabs/agent-explorer#81]
* step 1 i was assinged a new Vc to the DID (user 1) like:
```
Profile = {
  name ="sam",
  age = "18"
}
```	
* step 2 then User 2 create a SDR request for getting the name and age from the (user 1) Did.
* step 3 then i was able to see the SDR request Message in the "requests" page of the agent explorer UI.
* step 4 when i click on that Message then some time app crash and some time i am able to see the SDR page.
* step 5 after this i was selected the data that i want to share. but when i click on share button then `{"error":"Cannot read properties of undefined (reading 'jwt')"} ` this error comes.

**Comment by nickreynolds** [comment]
@vijay05155 Hi, I'm looking into this now. Is it possible for you to share the arguments you passed into the `createVerifiablePresentation` function? Also, are you sure that the DID used to generate the SDR has a `Secp256k1` signing key? That function will throw an exception if that type of key is not found

**Comment by nickreynolds** [comment]
I wasn't able to repro this exactly, but I believe this may have been fixed by my recent PR to improve SDR flows. At minimum, it should handle the error more gracefully and give more context to the error if we are able to repro still. Closing this issue for now but will re-open if we find repro steps on latest
